name: Publish Website to Web Hosting
on:
  push:
    branches:
      - master
jobs:
  civil_app: 
    name: civil_app
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!


      # Runs a set of commands using the runners shell
      - name: Run a multi-line ngfbfg script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: civil_app
        uses: hazemwehbi/civil_app@master
        with:
          server: ${{ secrets.SERVER}}
          username: ${{ secrets.USERNAME}}
          password: ${{ secrets.PASSWORD}}
